class Strings {
  static const encryptionKey =
      '2c9ad621595fdca833c40b8d1d6cc427939ab41605a03ee36b51c960b73a68f9';
  static bool isLoggedIn = false;
  static String get permit => "Permit";
  static String get workPermit => "Work Permit";
  static String get tbtMeeting => "TBT Meetings";
  static String get safetyInduction => "Safety Induction";
  static String get uaucs => "UA & UC";
  static String get incidentReport => "Incident Reports";
  static String get safetyTraining => "Safety Training";
  static String get specificTraining => "Job Specific Training";
  static String get training => "Training";
  static String get safetyReport => "Safety Report";
  static String get reporting => "Reporting";

  static List<String> fileTypes = [
    'jpg',
    'jpeg',
    'png',
    'gif',
    'bmp',
    'webp',
    'heic',
    'heif',
    'tiff',
    'tif',
    'pdf',
    'doc',
    'docx',
    'odt',
    'rtf',
    'txt',
    'md',
    'xls',
    'xlsx',
    'ods',
    'csv',
    'tsv',
  ];
  static String fcmToken = "";
  static String userId = "";
  static String roleName = "";
  static String userName = "";
  static String locationName = "";
  static dynamic project;
  static dynamic userDetails;
  static dynamic notifications;
  static List<dynamic> permisssions = [
    "Read",
    "Write",
    "Delete",
    "Manage",
    "Moderate",
    "Inspect",
    "UAUC Prevention Action",
    "Workpermit Creation",
    "UAUC Creation",
    "Safety Creation",
    "roles.read",
    "roles.write",
    "roles.delete",
    "roles.view",
    "roles.manage",
    "roles.inspect",
    "user.read",
    "user.write",
    "user.delete",
    "user.view",
    "user.manage",
    "user.inspect",
    "labour.read",
    "labour.write",
    "labour.delete",
    "labour.view",
    "labour.manage",
    "labour.inspect",
    "subcontractors.read",
    "subcontractors.write",
    "subcontractors.delete",
    "subcontractors.view",
    "subcontractors.manage",
    "subcontractors.inspect",
    "event.read",
    "event.write",
    "event.delete",
    "event.view",
    "event.manage",
    "event.inspect",
    "inventory.read",
    "inventory.write",
    "inventory.delete",
    "inventory.view",
    "inventory.manage",
    "inventory.inspect",
    "items.read",
    "items.write",
    "items.delete",
    "items.view",
    "items.manage",
    "items.inspect",
    "format.read",
    "format.write",
    "format.delete",
    "format.view",
    "format.manage",
    "format.inspect",
    "project.read",
    "project.write",
    "project.delete",
    "project.view",
    "project.manage",
    "project.inspect",
    "category.read",
    "category.write",
    "category.delete",
    "category.view",
    "category.manage",
    "category.inspect",
    "safetyinduction.read",
    "safetyinduction.write",
    "safetyinduction.delete",
    "safetyinduction.view",
    "safetyinduction.manage",
    "safetyinduction.inspect",
    "tbtmeeting.read",
    "tbtmeeting.write",
    "tbtmeeting.delete",
    "tbtmeeting.view",
    "tbtmeeting.manage",
    "tbtmeeting.inspect",
    "incident.read",
    "incident.write",
    "incident.delete",
    "incident.view",
    "incident.manage",
    "incident.inspect",
    "inspection.read",
    "inspection.write",
    "inspection.delete",
    "inspection.view",
    "inspection.manage",
    "inspection.inspect",
    "specifictraining.read",
    "specifictraining.write",
    "specifictraining.delete",
    "specifictraining.view",
    "specifictraining.manage",
    "specifictraining.inspect",
    "uauc.read",
    "uauc.write",
    "uauc.delete",
    "uauc.view",
    "uauc.manage",
    "uauc.inspect",
    "goodpractices.read",
    "goodpractices.write",
    "goodpractices.delete",
    "goodpractices.view",
    "goodpractices.manage",
    "goodpractices.inspect",
    "violationnotice.read",
    "violationnotice.write",
    "violationnotice.delete",
    "violationnotice.view",
    "violationnotice.manage",
    "violationnotice.inspect",
    "checklist.read",
    "checklist.write",
    "checklist.delete",
    "checklist.view",
    "checklist.manage",
    "checklist.inspect",
    "workpermit.read",
    "workpermit.write",
    "workpermit.delete",
    "workpermit.view",
    "workpermit.manage",
    "workpermit.inspect",
    "workpermitdaily.read",
    "workpermitdaily.write",
    "workpermitdaily.delete",
    "workpermitdaily.view",
    "workpermitdaily.manage",
    "workpermitdaily.inspect",
    "rating.read",
    "rating.write",
    "rating.delete",
    "rating.view",
    "rating.manage",
    "rating.inspect",
    "projects.read",
    "projects.write",
    "projects.delete",
    "projects.view",
    "projects.manage",
    "projects.inspect",
    "trade.read",
    "trade.write",
    "trade.delete",
    "trade.view",
    "trade.manage",
    "trade.inspect",
    "topic.read",
    "topic.write",
    "topic.delete",
    "topic.view",
    "topic.manage",
    "topic.inspect",
    "hazards.read",
    "hazards.write",
    "hazards.delete",
    "hazards.view",
    "hazards.manage",
    "hazards.inspect",
    "tools.read",
    "tools.write",
    "tools.delete",
    "tools.view",
    "tools.manage",
    "tools.inspect",
    "machinetools.read",
    "machinetools.write",
    "machinetools.delete",
    "machinetools.view",
    "machinetools.manage",
    "machinetools.inspect",
    "equipments.read",
    "equipments.write",
    "equipments.delete",
    "equipments.view",
    "equipments.manage",
    "equipments.inspect",
    "ppes.read",
    "ppes.write",
    "ppes.delete",
    "ppes.view",
    "ppes.manage",
    "ppes.inspect",
    "item.read",
    "item.write",
    "item.delete",
    "item.view",
    "item.manage",
    "item.inspect",
    "permitstype.read",
    "permitstype.write",
    "permitstype.delete",
    "permitstype.view",
    "permitstype.manage",
    "permitstype.inspect",
    "prefilledchecklist.read",
    "prefilledchecklist.write",
    "prefilledchecklist.delete",
    "prefilledchecklist.view",
    "prefilledchecklist.manage",
    "prefilledchecklist.inspect",
    "fields.read",
    "fields.write",
    "fields.delete",
    "fields.view",
    "fields.manage",
    "fields.inspect",
    "riskrating.read",
    "riskrating.write",
    "riskrating.delete",
    "riskrating.view",
    "riskrating.manage",
    "riskrating.inspect",
    "role.read",
    "role.write",
    "role.delete",
    "role.view",
    "role.manage",
    "role.inspect",
    "feedback.read",
    "feedback.write",
    "feedback.delete",
    "feedback.view",
    "feedback.manage",
    "feedback.inspect",
    "notifications.read",
    "notifications.write",
    "notifications.delete",
    "notifications.view",
    "notifications.manage",
    "notifications.inspect",
    "safetyreport.read",
    "safetyreport.write",
    "safetyreport.delete",
    "safetyreport.view",
    "safetyreport.manage",
    "safetyreport.inspect",
    "labourRec.read",
    "labourRec.write",
    "labourRec.delete",
    "labourRec.view",
    "labourRec.manage",
    "labourRec.inspect",
    "formfields.read",
    "formfields.write",
    "formfields.delete",
    "formfields.view",
    "formfields.manage",
    "formfields.inspect",
    "apk.read",
    "apk.write",
    "apk.delete",
    "apk.view",
    "apk.manage",
    "apk.inspect",
    "backup.read",
    "backup.write",
    "backup.delete",
    "backup.view",
    "backup.manage",
    "backup.inspect",
    "safetyaudit.read",
    "safetyaudit.write",
    "safetyaudit.delete",
    "safetyaudit.view",
    "safetyaudit.manage",
    "safetyaudit.inspect",
    "safetybudget.read",
    "safetybudget.write",
    "safetybudget.delete",
    "safetybudget.view",
    "safetybudget.manage",
    "safetybudget.inspect",
    "about:view",
    "projectDashboard:view",
    "settings:view",
    "profile:view",
    "notificationsender:view",
    "FilesManagement:view",
    "management:view",
    "workpermitformat:view",
    "documentformat:view",
    "checklistformat:view",
    "dashboard:view",
    "Labour Registration",
    "Labour Management",
    "Labour Registration",
  ];
  static List<dynamic> projects = [];
  static List<dynamic> mappedProjects = [];
  static List<dynamic> permitsType = [];
  static List<dynamic> users = [];
  static List<dynamic> safetyUsers = [];
  static List<dynamic> managementUser = [];
  static List<dynamic> exeUsers = [];
  static List<dynamic> topics = [];
  static List<dynamic> riskRatings = [];
  static List<dynamic> tools = [];
  static List<dynamic> equipments = [];
  static List<dynamic> hazards = [];
  static List<dynamic> ppes = [];
  static List<dynamic> trades = [];
  static List<dynamic> workpermit = [];
  static List<dynamic> meetings = [];
  static List<dynamic> specific = [];
  static List<dynamic> uauc = [];
  static List<dynamic> induction = [];
  static List<dynamic> safetyreport = [];
  static List<dynamic> workpermitPageFild = [];
  static List<dynamic> prefilledChecklist = [];
  static List<dynamic> workpermitPageField = [];
  static List<dynamic> contractors = [];
  static List<dynamic> labourDetails = [];
  static List<dynamic> mobilisationPlans = [];
  static List<dynamic> labourCategories = [];
  static List<dynamic> zones = [];
  static List<dynamic> roles = [];
  static List<dynamic> teams = [];
  static List<dynamic> dailyInteractions = [];

  static final Map<String, dynamic> endpointToList = {
    "projects": projects,
    "mappedProjects": mappedProjects,
    "permitstype": permitsType,
    "user": users,
    "safetyuser": safetyUsers,
    "managementuser": managementUser,
    "exeuser": exeUsers,
    "permission": permisssions,
    "userid": userId,
    "topic": topics,
    "riskRating": riskRatings,
    "tools": tools,
    "equipments": equipments,
    "hazards": hazards,
    "ppe": ppes,
    "trade": trades,
    "project": project,
    "userDetails": userDetails,
    "workpermit": workpermit,
    "meeting": meetings,
    "specific": specific,
    "uauc": uauc,
    "induction": induction,
    "safetyreport": safetyreport,
    "prefilledchecklist": prefilledChecklist,

    // Dynamic endpoints
    "contractors": contractors,
    "labour-details": labourDetails,
    "mobilisation-plans": mobilisationPlans,
    "labour-categories": labourCategories,
    "zones": zones,
    "roles": roles,
    "teams": teams,
    "daily-interactions": dailyInteractions,
  };
}
